#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update
sudo apt-get -y install nginx

# sudo mkdir -p /var/www/htm
sudo touch /var/www/html/index.html
# sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World" > /var/www/html/index.html

sudo service nginx restart
