#!/usr/bin/bash

sed -i '/frontend myfrontend/,/backend mybackend/d' testfile
sed -i '/frontend myfrontend/a \
    bind *:80\n\
    default_backend mybackend\n\
\n\
backend mybackend\n\
    server server1 192.168.1.101:80 check\n\
    server server2 192.168.1.102:80 check' testfile
