#!/usr/bin/env bash
# 101-manage_my_process

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PID_FILE="/var/run/my_process.pid"
PROCESS_SCRIPT="${SCRIPT_PATH}/manage_my_process"

start_process() {
    nohup "${PROCESS_SCRIPT}" > /dev/null 2>&1 &
    echo $! > $PID_FILE
    echo "manage_my_process started"
}

stop_process() {
    pid=$(cat $PID_FILE)
    kill -TERM "$pid"
    rm -f $PID_FILE
    echo "manage_my_process stopped"
}

restart_process() {
    pid=$(cat $PID_FILE)
    kill -TERM "$pid"
    rm -f $PID_FILE
    nohup "${PROCESS_SCRIPT}" > /dev/null 2>&1 &
    echo $! > $PID_FILE
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
