#!/bin/bash

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PID_FILE="/var/run/my_process.pid"
PROCESS_SCRIPT="${SCRIPT_PATH}/manage_my_process"

start_process() {
    if [ -e $PID_FILE ]; then
        echo "Error: Process already running. Check $PID_FILE"
        exit 1
    fi

    nohup "${PROCESS_SCRIPT}" > /dev/null 2>&1 &
    echo $! > $PID_FILE
    echo "manage_my_process started"
}

stop_process() {
    if [ -e $PID_FILE ]; then
        pid=$(cat $PID_FILE)
        kill -TERM "$pid"
        rm -f $PID_FILE
        echo "manage_my_process stopped"
    else
        echo "Error: Process not running. $PID_FILE not found."
    fi
}

restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

