#!/usr/bin/env bash
#change local host with 127.0.0.2
#facebook.com change it to 8.8.8.8

if grep -q docker /proc/1/cgroup; then
    echo "Running inside Docker container."
else
    echo "Not running inside Docker container."
fi


cp /etc/hosts ~/hosts.new
echo "172.0.0.2       localhost" > ~/hosts.new
echo "8.8.8.8       facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
