#!/usr/bin/env bash
# Run Nginx as Nginx

# apache currently runs on the port needed :8080
pkill apache2

# make nginx run on all port :8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# change user to nginx in all nginx files
sudo chown -R nginx:nginx /etc/nginx /var/log/nginx /usr/share/nginx

#give read and write access to the config folder
chmod 0644 /etc/nginx/nginx.conf

# run nginx as new user
su nginx -c nginx
