#!/usr/bin/env bash
# Run Nginx as Nginx

# Update Nginx configuration to run as nginx user
sudo sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx server block to listen on port 8080 for all IPs
sudo sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
